AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-golang

  Sample SAM Template for lambda-golang go1.x
Globals:
  Function:
    Timeout: 3

Resources:
  getAllDocumentsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Timeout: 300
      MemorySize: 128
      CodeUri: /Users/rjromero/Documents/git/go/src/github.com/ricardojonathanromero/lambda-golang-example/get-all-documents-lambda
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        GetAllDocuments:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          ENV: local
          DYNAMODB_URL: http://dynamodb-local-integration-test:8000
          DYNAMODB_TABLE_NAME: users
          LOG_LEVEL: debug
